trigger:
- certification_feature
- main

pr:
- main

pool:
  name: 'Default'  # Replace with the name of your agent pool

jobs:
- job: Build
  steps:
  - checkout: self
  - script: |
      cd $(Build.SourcesDirectory)
      git checkout main
      git pull origin main
      git merge certification_feature
    displayName: 'Build'
